# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x07scalper*/\n\x08\x45xchange\x12\x18\n\x14\x45XCHANGE_UNSPECIFIED\x10\x00\x12\t\n\x05UPBIT\x10\x01*G\n\nChangeType\x12\x1b\n\x17\x43HANGE_TYPE_UNSPECIFIED\x10\x00\x12\x08\n\x04RISE\x10\x01\x12\x08\n\x04\x45VEN\x10\x02\x12\x08\n\x04\x46\x41LL\x10\x03*3\n\x06\x41skBid\x12\x17\n\x13\x41SK_BID_UNSPECIFIED\x10\x00\x12\x07\n\x03\x41SK\x10\x01\x12\x07\n\x03\x42ID\x10\x02*E\n\nStreamType\x12\x1b\n\x17STREAM_TYPE_UNSPECIFIED\x10\x00\x12\x0c\n\x08SNAPSHOT\x10\x01\x12\x0c\n\x08REALTIME\x10\x02\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_EXCHANGE']._serialized_start=25
  _globals['_EXCHANGE']._serialized_end=72
  _globals['_CHANGETYPE']._serialized_start=74
  _globals['_CHANGETYPE']._serialized_end=145
  _globals['_ASKBID']._serialized_start=147
  _globals['_ASKBID']._serialized_end=198
  _globals['_STREAMTYPE']._serialized_start=200
  _globals['_STREAMTYPE']._serialized_end=269
# @@protoc_insertion_point(module_scope)
