# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: market_data.proto
# Protobuf Python Version: 5.29.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    3,
    '',
    'market_data.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2
from data_ingestion.infrastructure.proto_generated import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11market_data.proto\x12\x07scalper\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x0c\x63ommon.proto\"\x8c\x03\n\x05Trade\x12#\n\x08\x65xchange\x18\x01 \x01(\x0e\x32\x11.scalper.Exchange\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x13\n\x0btrade_price\x18\x03 \x01(\x01\x12\x14\n\x0ctrade_volume\x18\x04 \x01(\x01\x12 \n\x07\x61sk_bid\x18\x05 \x01(\x0e\x32\x0f.scalper.AskBid\x12\x1a\n\x12prev_closing_price\x18\x06 \x01(\x01\x12#\n\x06\x63hange\x18\x07 \x01(\x0e\x32\x13.scalper.ChangeType\x12\x14\n\x0c\x63hange_price\x18\x08 \x01(\x01\x12\x33\n\x0ftrade_timestamp\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x15\n\rsequential_id\x18\n \x01(\x03\x12(\n\x0bstream_type\x18\x0b \x01(\x0e\x32\x13.scalper.StreamType\x12\x36\n\x12received_timestamp\x18\x0c \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"-\n\x0eOrderBookLevel\x12\r\n\x05price\x18\x01 \x01(\x01\x12\x0c\n\x04size\x18\x02 \x01(\x01\"\xd9\x02\n\x0fOrderBookUpdate\x12#\n\x08\x65xchange\x18\x01 \x01(\x0e\x32\x11.scalper.Exchange\x12\x0c\n\x04\x63ode\x18\x02 \x01(\t\x12\x16\n\x0etotal_ask_size\x18\x03 \x01(\x01\x12\x16\n\x0etotal_bid_size\x18\x04 \x01(\x01\x12%\n\x04\x61sks\x18\x05 \x03(\x0b\x32\x17.scalper.OrderBookLevel\x12%\n\x04\x62ids\x18\x06 \x03(\x0b\x32\x17.scalper.OrderBookLevel\x12(\n\x0bstream_type\x18\x07 \x01(\x0e\x32\x13.scalper.StreamType\x12\x33\n\x0f\x65vent_timestamp\x18\x08 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\x12\x36\n\x12received_timestamp\x18\t \x01(\x0b\x32\x1a.google.protobuf.Timestampb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'market_data_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TRADE']._serialized_start=78
  _globals['_TRADE']._serialized_end=474
  _globals['_ORDERBOOKLEVEL']._serialized_start=476
  _globals['_ORDERBOOKLEVEL']._serialized_end=521
  _globals['_ORDERBOOKUPDATE']._serialized_start=524
  _globals['_ORDERBOOKUPDATE']._serialized_end=869
# @@protoc_insertion_point(module_scope)
